services:
  redis:
    image: redis:7.4-alpine
    container_name: media-redis
    ports:
      - "8982:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass redis123 --appendonly yes # Ensures data isn't lost on restart
    restart: always
    networks:
      - media_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - media_network

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka2
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - media_network
  mysql:
    image: mysql:8.0
    container_name: mysql-media-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: media_events_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - media_network

  mysql-user:
    image: mysql:8.0
    container_name: mysql-user-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: user_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql-user
    networks:
      - media_network

  redis-rate-limit:
    image: redis:7.4-alpine
    container_name: rate-limit-redis
    ports:
      - "8983:6379"
    volumes:
      - redis_data:/data_limit
    command: redis-server --requirepass redis123 --appendonly yes # Ensures data isn't lost on restart
    restart: always
    networks:
      - media_network


volumes:
  redis_data:
  mysql_data:
  mysql-user:

networks:
  media_network:
    driver: bridge