spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3307/user_db
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8993

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: thisIsASecretKeyForJWTGenerationAndIsNotTooShortAndNotTooLongEitherAndShouldBeKeptSafeAndSecure
  expiration: 3600000 # 1 hour in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: health,info,matrics,loggers
  endpoint:
    health:
      show-details: always
