spring.application.name=event_api_service


server.port=8981

#Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=8982
spring.data.redis.timeout=2000ms
spring.data.redis.password=redis123